name: Publish package to GitHub Packages
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '10.18.0'
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install --legacy-peer-deps
      - run: npm prebuild
      - run: npm run release:prepare
      - run: npm run npm:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}